# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: db0e9b214936064e6e081b16fa4db046102113ee0fc09796ad7f63f614ce8b30c48cfa616a1af43f51439f453e67f3273c08d1c49c6d01d515d3b8e41a7e3b58

test:
  secret_key_base: a458b2bcc435d0d6b469016afc69bb89e1750c2f2712a0be344b9e710ef240be3c5445fc9697bd6251f6109754631a62da8a21fc6af91161edf29dba242a7f60

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
